services:
  - type: web
    name: onsh-backend
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 10000
      - key: REDIS_URL
        sync: false
      - key: LIVEKIT_URL
        value: wss://onshvideowatching-jbxlr1u5.livekit.cloud
      - key: LIVEKIT_API_KEY
        value: APIaRVBdror5c2K
      - key: LIVEKIT_API_SECRET
        sync: false
